version: '2'
services:
    itgmapp-app:
        image: itgmapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://itgmapp-postgresql:5432/itgmapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    itgmapp-postgresql:
        extends:
            file: postgresql.yml
            service: itgmapp-postgresql
